---
# tasks file for configure-openshift-virt
- name: Validate User Login
  ansible.builtin.include_tasks: validate-login.yml
  tags: always
- name: Install and configure OpenShift Data Foundation
  ansible.builtin.include_tasks: configure-odf.yml
  tags: configure_odf